/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;
import static org.testng.Assert.*;

import java.io.ByteArrayInputStream;

public class PalindromeTest {
       
	@DataProvider(name="palindromeCases")
    private Object[][] names() {
        return new Object[][] {{"anna"},
                {"kayak"},
                {""},
                {"hannah"},
                {"AllillA"}};
    }
    @Test (dataProvider = "palindromeCases")
  
    public void whetherReversedStringIstheSameEntered(String name){
		System.setIn(new ByteArrayInputStream((name).getBytes()));
		Palindrome str = new Palindrome();
		String strGiven = str.AskUserForAString();
		String strReversed = str.analysePalindrome(strGiven);
		assertEquals(strGiven, strReversed, "Reversed string are palindromes");
	}
   
    @Test 
    public void printsIsCorrectPallindrome(){
    	Palindrome str = new Palindrome();
    	assertEquals(str.printPalindrome("ababa", str.analysePalindrome("ababa")),"String 'ababa' is a palindrome.");
    }
    
    @Test 
    public void printsIsNotPallindrome(){
    	Palindrome str = new Palindrome();
    	assertEquals(str.printPalindrome("ababab", str.analysePalindrome("ababab")),"String 'ababab' is not a palindrome.");
    }
}
